### PR TITLE
Schedule Deneb on Sepolia & Holesky

### PR DESCRIPTION
**Pull request by michaelsproul**
Update Lighthouse to v4.6.0 which schedules Deneb on Sepolia and Holesky:

> `$ RUST_LOG=eleel target/debug/eleel --network sepolia --ee-jwt-secret ~/.lighthouse/eleel.hex --controller-jwt-secret ~/.lighthouse/eleel.hex --client-jwt-secrets example-secrets.toml`

Running Eleel shows the correct fork epochs:

> 2024-01-25T00:52:11.775616Z  INFO eleel::multiplexer: fork schedule bellatrix_fork_epoch=Some(Epoch(100)) capella_fork_epoch=Some(Epoch(56832)) **deneb_fork_epoch=Some(Epoch(132608))**

> `$ RUST_LOG=eleel target/debug/eleel --network holesky --ee-jwt-secret ~/.lighthouse/eleel.hex --controller-jwt-secret ~/.lighthouse/eleel.hex --client-jwt-secrets example-secrets.toml`

> 2024-01-25T00:53:28.860528Z  INFO eleel::multiplexer: fork schedule bellatrix_fork_epoch=Some(Epoch(0)) capella_fork_epoch=Some(Epoch(256)) **deneb_fork_epoch=Some(Epoch(29696))**

### CODE REVIEW

**Comment by michaelsproul** [comment]
cc @Savid @samcm

We're ready this time!

**Comment by Savid** [comment]
you're a gentleman and scholar! @michaelsproul

**Review by Savid — APPROVED** [review]

**Comment by michaelsproul** [comment]
thanks! will merge once CI passes 🤙

**Comment by samcm** [comment]
Thanks @michaelsproul! 👑

**Pull request merged**
